name: CI

on:
  push:
    branches:
        main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run lint:ci
      - run: yarn run test
